//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganhBookingHotel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int Phong_id { get; set; }
        public string tenphong { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public System.DateTime ngaydacphong { get; set; }
        public System.DateTime ngaytraphong { get; set; }
        public int thanhtoan { get; set; }
        public int phongchidinh { get; set; }
        public Nullable<byte> succhua { get; set; }
        public Nullable<decimal> tongsotien { get; set; }
    
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
