//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganhBookingHotel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int thanhtoan_id { get; set; }
        public byte datphong_id { get; set; }
        public int hinhthucthanhtoan_id { get; set; }
        public decimal sotienthanhtoan { get; set; }
    
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
    }
}
