//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganhBookingHotel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoaiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public int theloaiphong_id { get; set; }
        public string tenphong { get; set; }
        public string mota { get; set; }
        public Nullable<decimal> giaphong { get; set; }
        public byte succhua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
